        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (155, 'Eggs', 'Severe', 'Hives');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (119, 'Eggs', 'Mild', 'Redness');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (199, 'Wheat', 'Severe', 'Swelling');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (113, 'Shellfish', 'Mild', 'Swelling');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (147, 'Soy', 'Severe', 'Itching');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (175, 'Wheat', 'Moderate', 'Swelling');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (197, 'Milk', 'Moderate', 'Hives');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (121, 'Fish', 'Moderate', 'Swelling');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (104, 'Peanuts', 'Moderate', 'Hives');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (103, 'Eggs', 'Severe', 'Anaphylaxis');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (109, 'Peanuts', 'Mild', 'Anaphylaxis');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (140, 'Tree nuts', 'Mild', 'Anaphylaxis');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (153, 'Peanuts', 'Severe', 'Rash');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (176, 'Shellfish', 'Severe', 'Hives');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (115, 'Eggs', 'Moderate', 'Swelling');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (111, 'Tree nuts', 'Severe', 'Swelling');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (177, 'Milk', 'Mild', 'Hives');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (137, 'Soy', 'Severe', 'Swelling');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (144, 'Soy', 'Mild', 'Itching');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (126, 'Fish', 'Severe', 'Redness');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (153, 'Shellfish', 'Mild', 'Redness');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (193, 'Fish', 'Severe', 'Itching');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (102, 'Peanuts', 'Mild', 'Redness');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (145, 'Fish', 'Severe', 'Swelling');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (131, 'Soy', 'Mild', 'Hives');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (170, 'Shellfish', 'Moderate', 'Redness');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (197, 'Soy', 'Moderate', 'Anaphylaxis');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (169, 'Soy', 'Mild', 'Itching');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (164, 'Tree nuts', 'Mild', 'Itching');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (135, 'Shellfish', 'Mild', 'Anaphylaxis');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (131, 'Peanuts', 'Mild', 'Rash');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (113, 'Shellfish', 'Severe', 'Rash');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (159, 'Peanuts', 'Moderate', 'Itching');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (107, 'Eggs', 'Moderate', 'Hives');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (195, 'Fish', 'Moderate', 'Hives');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (182, 'Peanuts', 'Moderate', 'Anaphylaxis');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (136, 'Wheat', 'Mild', 'Swelling');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (141, 'Peanuts', 'Severe', 'Swelling');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (198, 'Eggs', 'Moderate', 'Rash');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (108, 'Milk', 'Moderate', 'Anaphylaxis');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (120, 'Soy', 'Moderate', 'Itching');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (131, 'Fish', 'Severe', 'Redness');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (153, 'Wheat', 'Mild', 'Swelling');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (134, 'Shellfish', 'Mild', 'Itching');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (181, 'Tree nuts', 'Mild', 'Swelling');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (139, 'Tree nuts', 'Moderate', 'Hives');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (137, 'Peanuts', 'Severe', 'Hives');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (129, 'Fish', 'Severe', 'Itching');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (149, 'Fish', 'Mild', 'Redness');
        INSERT INTO PatientAllergies (patient_id, allergy, severity, reaction) VALUES (163, 'Wheat', 'Severe', 'Hives');

        UPDATE patients SET insurance_id = 15 WHERE patient_id = 104;
        UPDATE patients SET insurance_id = 16 WHERE patient_id = 116;
        UPDATE patients SET insurance_id = 17 WHERE patient_id = 110;
        UPDATE patients SET insurance_id = 18 WHERE patient_id = 126;
        UPDATE patients SET insurance_id = 19 WHERE patient_id = 131;
        UPDATE patients SET insurance_id = 20 WHERE patient_id = 144;
        UPDATE patients SET insurance_id = 21 WHERE patient_id = 188;
        UPDATE patients SET insurance_id = 22 WHERE patient_id = 183;
        UPDATE patients SET insurance_id = 23 WHERE patient_id = 184;
        UPDATE patients SET insurance_id = 24 WHERE patient_id = 127;
        UPDATE patients SET insurance_id = 25 WHERE patient_id = 105;
        UPDATE patients SET insurance_id = 26 WHERE patient_id = 146;
        UPDATE patients SET insurance_id = 27 WHERE patient_id = 140;
        UPDATE patients SET insurance_id = 28 WHERE patient_id = 199;
        UPDATE patients SET insurance_id = 29 WHERE patient_id = 120;
        UPDATE patients SET insurance_id = 30 WHERE patient_id = 142;
        UPDATE patients SET insurance_id = 31 WHERE patient_id = 137;
        UPDATE patients SET insurance_id = 32 WHERE patient_id = 178;
        UPDATE patients SET insurance_id = 33 WHERE patient_id = 166;
        UPDATE patients SET insurance_id = 34 WHERE patient_id = 151;
        UPDATE patients SET insurance_id = 35 WHERE patient_id = 170;
        UPDATE patients SET insurance_id = 36 WHERE patient_id = 113;
        UPDATE patients SET insurance_id = 37 WHERE patient_id = 185;
        UPDATE patients SET insurance_id = 38 WHERE patient_id = 130;
        UPDATE patients SET insurance_id = 39 WHERE patient_id = 176;
        UPDATE patients SET insurance_id = 40 WHERE patient_id = 136;
        UPDATE patients SET insurance_id = 41 WHERE patient_id = 182;
        UPDATE patients SET insurance_id = 42 WHERE patient_id = 155;
        UPDATE patients SET insurance_id = 43 WHERE patient_id = 192;
        UPDATE patients SET insurance_id = 44 WHERE patient_id = 112;
        UPDATE patients SET insurance_id = 45 WHERE patient_id = 179;
        UPDATE patients SET insurance_id = 46 WHERE patient_id = 149;
        UPDATE patients SET insurance_id = 47 WHERE patient_id = 165;
        UPDATE patients SET insurance_id = 48 WHERE patient_id = 181;
        UPDATE patients SET insurance_id = 49 WHERE patient_id = 190;
        UPDATE patients SET insurance_id = 50 WHERE patient_id = 124;
        UPDATE patients SET insurance_id = 51 WHERE patient_id = 196;
        UPDATE patients SET insurance_id = 52 WHERE patient_id = 114;
        UPDATE patients SET insurance_id = 53 WHERE patient_id = 177;
        UPDATE patients SET insurance_id = 54 WHERE patient_id = 186;
        UPDATE patients SET insurance_id = 55 WHERE patient_id = 156;
        UPDATE patients SET insurance_id = 56 WHERE patient_id = 147;
        UPDATE patients SET insurance_id = 57 WHERE patient_id = 194;
        UPDATE patients SET insurance_id = 58 WHERE patient_id = 189;
        UPDATE patients SET insurance_id = 59 WHERE patient_id = 172;
        UPDATE patients SET insurance_id = 60 WHERE patient_id = 111;
        UPDATE patients SET insurance_id = 61 WHERE patient_id = 123;
        UPDATE patients SET insurance_id = 62 WHERE patient_id = 134;
        UPDATE patients SET insurance_id = 63 WHERE patient_id = 107;
        UPDATE patients SET insurance_id = 64 WHERE patient_id = 160;
        UPDATE patients SET insurance_id = 65 WHERE patient_id = 118;
        UPDATE patients SET insurance_id = 66 WHERE patient_id = 103;
        UPDATE patients SET insurance_id = 67 WHERE patient_id = 168;
        UPDATE patients SET insurance_id = 68 WHERE patient_id = 175;
        UPDATE patients SET insurance_id = 69 WHERE patient_id = 167;
        UPDATE patients SET insurance_id = 70 WHERE patient_id = 122;
        UPDATE patients SET insurance_id = 71 WHERE patient_id = 191;
        UPDATE patients SET insurance_id = 72 WHERE patient_id = 173;
        UPDATE patients SET insurance_id = 73 WHERE patient_id = 115;
        UPDATE patients SET insurance_id = 74 WHERE patient_id = 162;
        UPDATE patients SET insurance_id = 75 WHERE patient_id = 102;
        UPDATE patients SET insurance_id = 76 WHERE patient_id = 197;
        UPDATE patients SET insurance_id = 77 WHERE patient_id = 138;
        UPDATE patients SET insurance_id = 78 WHERE patient_id = 201;
